// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_3wRdxAYn9xTnaoLh1xURgcRRsCnpaGk',
    appId: '1:79338234029:web:4b8c5b24c63645c1696624',
    messagingSenderId: '79338234029',
    projectId: 'vendo-35469',
    authDomain: 'vendo-35469.firebaseapp.com',
    storageBucket: 'vendo-35469.appspot.com',
    measurementId: 'G-9WVBQFFR6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUma8lbgZybLW0VwWgctgsVb31WTOlsqs',
    appId: '1:79338234029:android:48d500e95248def8696624',
    messagingSenderId: '79338234029',
    projectId: 'vendo-35469',
    storageBucket: 'vendo-35469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClwDKfzGV_7ICoib-lk2rH0iw5IlKW5Lw',
    appId: '1:79338234029:ios:4b716b1ce9f0c8fc696624',
    messagingSenderId: '79338234029',
    projectId: 'vendo-35469',
    storageBucket: 'vendo-35469.appspot.com',
    iosClientId:
        '79338234029-gq3bidrq6liirpcrvb6oopj1mdrkhon4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClwDKfzGV_7ICoib-lk2rH0iw5IlKW5Lw',
    appId: '1:79338234029:ios:4b716b1ce9f0c8fc696624',
    messagingSenderId: '79338234029',
    projectId: 'vendo-35469',
    storageBucket: 'vendo-35469.appspot.com',
    iosClientId:
        '79338234029-gq3bidrq6liirpcrvb6oopj1mdrkhon4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendo',
  );
}
