name: vendo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  calendar_date_picker2: ^0.2.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  file_picker: ^5.0.1
  firebase_core: ^1.20.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  localization: ^2.1.0
  passwordfield: ^0.1.0
  share_plus: ^4.0.10+1
  table_calendar: ^3.0.6
  place_picker: ^0.9.19
  firebase_storage: ^10.3.5
  camera: ^0.10.0+1
  path_provider: ^2.0.11
  path: ^1.8.1
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.5
  qr_code_scanner: ^1.0.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
